package ro.cristivoicu.springbootrestless.fixtures.sprocket;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.transaction.annotation.Transactional;
import tools.jackson.databind.ObjectMapper;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

/**
 * Proof: {@link Sprocket} declares nothing but the entity + DTOs + Mapper (plus the escape-hatch
 * {@link SprocketCreateDataSource}), annotated {@code @RestlessEntity} - {@code
 * SprocketRepository} and {@code SprocketRestlessResource} are both compile-time generated by
 * {@code RestlessEntityProcessor}, yet the full CRUD surface works identically to a hand-written
 * or runtime-default resource.
 */
@SpringBootTest
@AutoConfigureMockMvc
@Transactional
class SprocketGeneratedResourceTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @Test
    void fullCrudCycleWorksThroughTheGeneratedResource() throws Exception {
        SprocketCreateModel create = new SprocketCreateModel();
        create.setName("Restless");
        create.setDescription("Annotation-driven CRUD");

        String createResponse = mockMvc.perform(post("/sprockets")
                        .contentType("application/json")
                        .content(objectMapper.writeValueAsString(create)))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.name").value("Restless"))
                .andReturn().getResponse().getContentAsString();
        long id = objectMapper.readTree(createResponse).get("id").asLong();

        mockMvc.perform(get("/sprockets/{id}", id))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.description").value("Annotation-driven CRUD"));

        mockMvc.perform(get("/sprockets"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.totalElements").value(1));

        SprocketUpdateModel update = new SprocketUpdateModel();
        update.setName("Restless Framework");
        update.setDescription("Updated");

        mockMvc.perform(put("/sprockets/{id}", id)
                        .contentType("application/json")
                        .content(objectMapper.writeValueAsString(update)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.name").value("Restless Framework"));

        mockMvc.perform(delete("/sprockets/{id}", id))
                .andExpect(status().isNoContent());

        mockMvc.perform(get("/sprockets/{id}", id))
                .andExpect(status().isNotFound());
    }

    @Test
    void createStillValidates() throws Exception {
        SprocketCreateModel invalid = new SprocketCreateModel();
        invalid.setName("");

        mockMvc.perform(post("/sprockets")
                        .contentType("application/json")
                        .content(objectMapper.writeValueAsString(invalid)))
                .andExpect(status().isBadRequest());
    }

    @Test
    void overriddenCreateDataSourceRunsInsteadOfTheDefault() throws Exception {
        // SprocketCreateDataSource (wired via @RestlessEntity(createDataSource = ...)) defaults
        // a blank description instead of leaving it blank, unlike the generated default's plain
        // field-by-field copy - proves the escape hatch actually took effect, not just compiled.
        SprocketCreateModel create = new SprocketCreateModel();
        create.setName("Restless");
        create.setDescription("");

        mockMvc.perform(post("/sprockets")
                        .contentType("application/json")
                        .content(objectMapper.writeValueAsString(create)))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.description").value("No description provided"));
    }
}
