package ro.cristivoicu.springbootrestless.fixtures.sprocket;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import ro.cristivoicu.springbootrestless.annotation.RestlessEntity;

/**
 * Test-only fixture (not shipped): entity + DTOs + Mapper are the only hand-written files here
 * beyond the escape-hatch {@link SprocketCreateDataSource}. {@code SprocketRestlessResource}
 * (and, since no hand-written {@code SprocketRepository} exists, {@code SprocketRepository}
 * too) are generated by {@code RestlessEntityProcessor} at compile time - proving the compile-
 * time generator still works as a framework mechanism, independent of any specific example
 * entity. See the {@code example} module's original {@code Project} entity, which this
 * fixture's role replaced when entities moved out of {@code app}.
 */
@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@RestlessEntity(basePath = "/sprockets", createDataSource = SprocketCreateDataSource.class)
public class Sprocket {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;

    private String description;
}
