package ro.cristivoicu.springbootrestless.example.entity.project;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import ro.cristivoicu.springbootrestless.annotation.RestlessEntity;

/**
 * Compile-time-generated proof: entity + DTOs + Mapper are the only hand-written files here
 * beyond the escape-hatch {@link ProjectCreateDataSource}. {@code ProjectRestlessResource} (and,
 * since no hand-written {@code ProjectRepository} exists, {@code ProjectRepository} too) are
 * generated by {@code RestlessEntityProcessor} at compile time from just this annotation - see
 * {@code target/generated-sources/annotations}. {@code createDataSource} demonstrates the
 * override attributes: {@link ProjectCreateDataSource} gets injected into the generated resource
 * instead of a generated {@code DefaultCreateDataSource} call, for logic the default can't
 * express (defaulting a blank description).
 */
@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@RestlessEntity(basePath = "/projects", createDataSource = ProjectCreateDataSource.class)
public class Project {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;

    private String description;
}
