package ro.cristivoicu.springbootrestless.entity.project;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.transaction.annotation.Transactional;
import tools.jackson.databind.ObjectMapper;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

/**
 * Step 1 proof: {@code Project} declares nothing but the entity + DTOs + Mapper, annotated
 * {@code @RestlessEntity} - {@code ProjectRepository} and {@code ProjectRestlessResource} are
 * both compile-time generated by {@code RestlessEntityProcessor} (see
 * {@code target/generated-sources/annotations}), yet the full CRUD surface works identically to
 * a hand-written or runtime-default resource.
 */
@SpringBootTest
@AutoConfigureMockMvc
@Transactional
class ProjectGeneratedResourceTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @Test
    void fullCrudCycleWorksThroughTheGeneratedResource() throws Exception {
        ProjectCreateModel create = new ProjectCreateModel();
        create.setName("Restless");
        create.setDescription("Annotation-driven CRUD");

        String createResponse = mockMvc.perform(post("/projects")
                        .contentType("application/json")
                        .content(objectMapper.writeValueAsString(create)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.name").value("Restless"))
                .andReturn().getResponse().getContentAsString();
        long id = objectMapper.readTree(createResponse).get("id").asLong();

        mockMvc.perform(get("/projects/{id}", id))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.description").value("Annotation-driven CRUD"));

        mockMvc.perform(get("/projects"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.totalElements").value(1));

        ProjectUpdateModel update = new ProjectUpdateModel();
        update.setName("Restless Framework");
        update.setDescription("Updated");

        mockMvc.perform(put("/projects/{id}", id)
                        .contentType("application/json")
                        .content(objectMapper.writeValueAsString(update)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.name").value("Restless Framework"));

        mockMvc.perform(delete("/projects/{id}", id))
                .andExpect(status().isNoContent());

        mockMvc.perform(get("/projects/{id}", id))
                .andExpect(status().isNotFound());
    }

    @Test
    void overriddenCreateDataSourceRunsInsteadOfTheDefault() throws Exception {
        // ProjectCreateDataSource (wired via @RestlessEntity(createDataSource = ...)) defaults
        // a blank description instead of leaving it blank, unlike the generated default's plain
        // field-by-field copy - proves the escape hatch actually took effect, not just compiled.
        ProjectCreateModel create = new ProjectCreateModel();
        create.setName("Restless");
        create.setDescription("");

        mockMvc.perform(post("/projects")
                        .contentType("application/json")
                        .content(objectMapper.writeValueAsString(create)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.description").value("No description provided"));
    }

    @Test
    void createStillValidates() throws Exception {
        ProjectCreateModel invalid = new ProjectCreateModel();
        invalid.setName("");

        mockMvc.perform(post("/projects")
                        .contentType("application/json")
                        .content(objectMapper.writeValueAsString(invalid)))
                .andExpect(status().isBadRequest());
    }
}
